Add Exhibition Title facet to Public Browser
collectionspace/cspace-public-browser.js pull request #4
Opened 2021-03-25 10:24 UTC by uneebsaleem

2021-03-26 17:54 UTC, ray-lee requested changes
A few changes needed. Thanks!

2021-03-26 17:54 UTC, ray-lee commented on src/config/default.js
> +            id: 'filter.title.label',
The convention is to use the filter name in the message id, so this should be `filter.exhibitionTitle.label`.

2021-03-26 17:54 UTC, ray-lee commented on src/config/default.js
> +            id: 'filter.title.shortLabel',
The convention is to use the filter name in the message id, so this should be `filter.exhibitionTitle. shortLabel`.

2021-03-26 17:54 UTC, ray-lee commented on src/config/default.js
> +            defaultMessage: 'exhibitionTitle',
The message should be human readable. Please make it `Exhibition title`.

2021-03-26 17:54 UTC, ray-lee commented on src/config/default.js
> +          'exhibitionTitle'
The message should be human readable. Please make it `Exhibition title`.

2021-03-26 22:23 UTC, uneebsaleem commented
@ray-lee fixed and pushed!

2021-04-16 22:48 UTC, ray-lee commented
Thanks!

2021-04-16 22:48 UTC, merged